#! /usr/bin/env ruby

raise "Usage: ./script/emergency [path]" if ARGV.length < 1

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'emergency'

debug = (ARGV[2]).to_s =~ /(-d|debug)/ ? true : false

Emergency::Runner.run!(ARGV[0], debug)