#! /usr/bin/env ruby

raise "Usage: ./script/emergency [path]" if ARGV.length < 1

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'emergency'

options = ARGV.flatten
record  = options.include?("record")
verbose = options.include?("verbose")

Emergency::Runner.run!(ARGV[0], {:record => record, :verbose => verbose})