#! /usr/bin/env ruby

$LOAD_PATH << File.expand_path(File.dirname(__FILE__)) + "/../../vendor/"
require 'rubygems'
require 'echo/server'

host = ARGV.shift
port = (ARGV.shift || 23000)
server  = Echo::Server.new(host, port)
server.start!
