#! /usr/bin/env ruby

# ./play <host> <port>

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'evasion'

host = ARGV.shift
port = ARGV.shift

evasion = Evasion::Dispatch.new({
  :host => host,
  :port => port
})

evasion.start!

