#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'voronoi'

host = ARGV.shift
port = ARGV.shift

voronoi = Voronoi::Dispatch.new({
  :host => host,
  :port => port
})

voronoi.start!

