#! /usr/bin/env ruby

require 'socket'               # Get sockets from stdlib
require 'rubygems'

hostname = 'localhost'
port = 2000

s = TCPSocket.open(hostname, port)

ARGV.each do |arg|
  s.puts arg
end

while line = s.gets   # Read lines from the socket
  puts line.chop      # And print with platform line terminator
end

s.close               # Close the socket when done
