#! /usr/bin/env ruby

lib_path = File.expand_path(File.dirname(__FILE__)) + "/lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'tipping'

no_tipping = Tipping::NoTipping.new({
  :name => ARGV[0],
  :port => (ARGV[1] || 4445).to_i
})
no_tipping.start!

