#! /usr/bin/env ruby

# ./play <host> <port>

lib_path = File.expand_path(File.dirname(__FILE__)) + "/../lib"
$LOAD_PATH << lib_path unless $LOAD_PATH.include? lib_path
require 'dating_game'

name = ARGV.shift
host = ARGV.shift
port = ARGV.shift

dating_game = DatingGame::Dispatch.new({
  :name => name,
  :host => host,
  :port => port
})

dating_game.start!

