$LOAD_PATH << File.expand_path(File.dirname(__FILE__)) + "/../../vendor/"
require 'rubygems'
require 'utils/measure'
require 'socket'
require 'voronoi/base'
require 'voronoi/client'
require 'voronoi/game'
require 'voronoi/player'
require 'voronoi/board'
require 'voronoi/move'
